name: Free Disk Space
description: Remove preinstalled runner components to free space for Nix/Rust builds.
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -euo pipefail
        echo "=============================================================================="
        echo "Freeing up disk space on CI system"
        echo "=============================================================================="

        df -h
        echo

        echo "Removing large directories (fast path)"
        sudo rm -rf \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /usr/share/swift
        df -h
